# Site settings
baseurl:          ""
url:              https://kk99corn.github.io

title:            이지혜, 프론트엔드 웹 개발자
description:      Freelance Front-end Web Developer
author:           이지혜 Jihye Lee
email:            ghe.lee19@gmail.com
lang:             ko
image:            /assets/image/common/feature.png # og_image, fb 고해상도 1200x630px, 8MB 이하

github_username:  designmeme
copyright:        © Jihye Lee

# Front matter defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      type: pages
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      type: posts
  - scope:
      path: en
    values:
      lang: en
  - scope:
      path: ko
    values:
      lang: ko
  - scope:
      path: _posts/en
    values:
      lang: en
      categories: en blog
  - scope:
      path: _posts/ko
    values:
      lang: ko
      categories: ko blog

# Build settings
permalink:        /:categories/:title/
timezone:         GMT
exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - README.md
  - node_modules
  - vendor
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  sass_dir: assets/sass
  style: compressed
kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
